name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: devmaster1987
          outputs: |
            output/github-contribution-grid-snake.svg

      - name: Commit snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update contribution snake"
          add: "output/github-contribution-grid-snake.svg"
